/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Qq188W48OsZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function WhatWeDo() {
  return (
    (<section className="bg-background py-12 md:py-16 lg:py-20">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-2xl font-bold text-primary mb-6 md:text-3xl text-center">What We Do</h2>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div
              className="bg-black text-white rounded-lg p-6 transition-colors duration-300 hover:bg-white hover:text-black">
              <div className="flex items-start">
                <CheckIcon className="w-5 h-5 mr-3 text-black group-hover:text-black" />
                <span>Capacity building for tax compliance</span>
              </div>
            </div>
            <div
              className="bg-black text-white rounded-lg p-6 transition-colors duration-300 hover:bg-white hover:text-black">
              <div className="flex items-start">
                <CheckIcon className="w-5 h-5 mr-3 text-black group-hover:text-black" />
                <span>Discussing IT systems and their impact on tax processes</span>
              </div>
            </div>
            <div
              className="bg-black text-white rounded-lg p-6 transition-colors duration-300 hover:bg-white hover:text-black">
              <div className="flex items-start">
                <CheckIcon className="w-5 h-5 mr-3 text-black group-hover:text-black" />
                <span>Explaining tax laws and regulations</span>
              </div>
            </div>
            <div
              className="bg-black text-white rounded-lg p-6 transition-colors duration-300 hover:bg-white hover:text-black">
              <div className="flex items-start">
                <CheckIcon className="w-5 h-5 mr-3 text-black group-hover:text-black" />
                <span>Developing fiscal policy ideas and strategies</span>
              </div>
            </div>
            <div
              className="bg-black text-white rounded-lg p-6 transition-colors duration-300 hover:bg-white hover:text-black">
              <div className="flex items-start">
                <CheckIcon className="w-5 h-5 mr-3 text-black group-hover:text-black" />
                <span>Providing timely tax updates and insights</span>
              </div>
            </div>
            <div
              className="bg-black text-white rounded-lg p-6 transition-colors duration-300 hover:bg-white hover:text-black">
              <div className="flex items-start">
                <CheckIcon className="w-5 h-5 mr-3 text-black group-hover:text-black" />
                <span>Facilitating research and discussions on tax-related topics</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>)
  );
}

function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}
